//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManager.Web {
    
    
    public partial class ContactForm {

        /// <summary>
        /// DataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CodeFluent.Runtime.Web.UI.WebControls.EntityDataSource DataSource;

	    
        /// <summary>
        /// default control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CodeFluent.Runtime.Web.UI.WebControls.EntityFormView defaultForm;
	    
    }
}
