//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftFluent.Samples.AngularJs.ReferenceData.Services
{
    using CodeFluent.Runtime;
    using CodeFluent.Runtime.Utilities;
    
    
    // CodeFluent Entities generated Tuesday, 03 February 2015 15:42.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.61214.0786")]
    public partial class ProductService : SoftFluent.Samples.AngularJs.ReferenceData.Services.IProductService
    {
        
        static ProductService()
        {
            CodeFluent.Runtime.Model.EntityDescriptor entityDescriptor = CodeFluent.Runtime.Model.ProjectDescriptor.Current.GetEntityDescriptor(typeof(SoftFluent.Samples.AngularJs.ReferenceData.Product), true);
            CodeFluent.Runtime.Model.ViewDescriptor viewDescriptor;
            CodeFluent.Runtime.Model.ViewPropertyDescriptor propertyDescriptor;
            viewDescriptor = new CodeFluent.Runtime.Model.ViewDescriptor(entityDescriptor, "default", CodeFluent.Runtime.Model.ViewDescriptorOptions.None);
            propertyDescriptor = new CodeFluent.Runtime.Model.ViewPropertyDescriptor(viewDescriptor, "Id", typeof(System.Guid), CodeFluent.Runtime.Model.ViewPropertyDescriptorOptions.IsKey);
            propertyDescriptor.Format = "N";
            propertyDescriptor = new CodeFluent.Runtime.Model.ViewPropertyDescriptor(viewDescriptor, "Name", typeof(string), CodeFluent.Runtime.Model.ViewPropertyDescriptorOptions.None);
            propertyDescriptor = new CodeFluent.Runtime.Model.ViewPropertyDescriptor(viewDescriptor, "Price", typeof(float), CodeFluent.Runtime.Model.ViewPropertyDescriptorOptions.None);
            propertyDescriptor = new CodeFluent.Runtime.Model.ViewPropertyDescriptor(viewDescriptor, "Star", typeof(int), CodeFluent.Runtime.Model.ViewPropertyDescriptorOptions.None);
            propertyDescriptor = new CodeFluent.Runtime.Model.ViewPropertyDescriptor(viewDescriptor, "Description", typeof(string), CodeFluent.Runtime.Model.ViewPropertyDescriptorOptions.None);
            propertyDescriptor = new CodeFluent.Runtime.Model.ViewPropertyDescriptor(viewDescriptor, "Orders", typeof(SoftFluent.Samples.AngularJs.OrderCollection), CodeFluent.Runtime.Model.ViewPropertyDescriptorOptions.IsCollection);
        }
        
        public virtual string Validate(SoftFluent.Samples.AngularJs.ReferenceData.Product product, string culture)
        {
            System.Globalization.CultureInfo cultureInfo = ConvertUtilities.ToCultureInfo(culture);
            SoftFluent.Samples.AngularJs.ReferenceData.Product product1 = product;
            if ((product1 == null))
            {
                return default(string);
            }
            return product1.Validate(cultureInfo);
        }
        
        public virtual bool Delete(SoftFluent.Samples.AngularJs.ReferenceData.Product product)
        {
            SoftFluent.Samples.AngularJs.ReferenceData.Product product1 = product;
            if ((product1 == null))
            {
                return CodeFluentPersistence.DefaultBooleanValue;
            }
            return product1.Delete();
        }
        
        public virtual SoftFluent.Samples.AngularJs.ReferenceData.Product Load(System.Guid id)
        {
            return SoftFluent.Samples.AngularJs.ReferenceData.Product.Load(id);
        }
        
        public virtual SoftFluent.Samples.AngularJs.ReferenceData.Product LoadById(System.Guid id)
        {
            return SoftFluent.Samples.AngularJs.ReferenceData.Product.LoadById(id);
        }
        
        public virtual bool Save(SoftFluent.Samples.AngularJs.ReferenceData.Product product)
        {
            SoftFluent.Samples.AngularJs.ReferenceData.Product product1 = product;
            if ((product1 == null))
            {
                return CodeFluentPersistence.DefaultBooleanValue;
            }
            return product1.Save();
        }
        
        public virtual SoftFluent.Samples.AngularJs.ReferenceData.Product LoadByEntityKey(string key)
        {
            return SoftFluent.Samples.AngularJs.ReferenceData.Product.LoadByEntityKey(key);
        }
        
        public virtual bool DeleteByKey(System.Guid id)
        {
            SoftFluent.Samples.AngularJs.ReferenceData.Product product = SoftFluent.Samples.AngularJs.ReferenceData.Product.Load(id);
            if ((product == null))
            {
                return CodeFluentPersistence.DefaultBooleanValue;
            }
            return product.Delete();
        }
        
        public virtual void SaveAll(SoftFluent.Samples.AngularJs.ReferenceData.ProductCollection productCollection)
        {
            SoftFluent.Samples.AngularJs.ReferenceData.ProductCollection productCollection1 = productCollection;
            productCollection1.SaveAll();
        }
        
        public virtual SoftFluent.Samples.AngularJs.ReferenceData.ProductCollection PageLoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions)
        {
            return SoftFluent.Samples.AngularJs.ReferenceData.ProductCollection.PageLoadAll(pageIndex, pageSize, pageOptions);
        }
        
        public virtual SoftFluent.Samples.AngularJs.ReferenceData.ProductCollection LoadAll()
        {
            return SoftFluent.Samples.AngularJs.ReferenceData.ProductCollection.LoadAll();
        }
        
        public virtual SoftFluent.Samples.AngularJs.ReferenceData.ProductCollection PageLoadProductsOrdersByOrder(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, string orderEntityKey)
        {
            if ((orderEntityKey == null))
            {
                throw new System.ArgumentNullException("orderEntityKey");
            }
            SoftFluent.Samples.AngularJs.Order order = SoftFluent.Samples.AngularJs.Order.LoadByEntityKey(orderEntityKey);
            return SoftFluent.Samples.AngularJs.ReferenceData.ProductCollection.PageLoadProductsOrdersByOrder(pageIndex, pageSize, pageOptions, order);
        }
        
        public virtual SoftFluent.Samples.AngularJs.ReferenceData.ProductCollection LoadProductsOrdersByOrder(string orderEntityKey)
        {
            if ((orderEntityKey == null))
            {
                throw new System.ArgumentNullException("orderEntityKey");
            }
            SoftFluent.Samples.AngularJs.Order order = SoftFluent.Samples.AngularJs.Order.LoadByEntityKey(orderEntityKey);
            return SoftFluent.Samples.AngularJs.ReferenceData.ProductCollection.LoadProductsOrdersByOrder(order);
        }
        
        public virtual System.IO.Stream JsonGet(CodeFluent.Runtime.Model.ProjectInvokeOptions options)
        {
            if ((options == null))
            {
                options = new CodeFluent.Runtime.Model.ProjectInvokeOptions();
            }
            options.EntityType = typeof(SoftFluent.Samples.AngularJs.ReferenceData.Product);
            return CodeFluent.Runtime.Model.ProjectDescriptor.JsonGet(options);
        }
        
        public virtual System.IO.Stream JsonPost(System.IO.Stream data)
        {
            CodeFluent.Runtime.Model.ProjectInvokeOptions options = CodeFluent.Runtime.Model.ProjectInvokeOptions.GetFromRequestUri();
            options.EntityType = typeof(SoftFluent.Samples.AngularJs.ReferenceData.Product);
            return CodeFluent.Runtime.Model.ProjectDescriptor.JsonPost(options, data);
        }
    }
}
