//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManager.Proxy
{
    using CodeFluent.Runtime;
    using CodeFluent.Runtime.Utilities;
    
    
    // CodeFluent Entities generated (http://www.softfluent.com). Date: Wednesday, 12 February 2014 15:18.
    // Build:1.0.61214.0762
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.61214.0762")]
    [System.ComponentModel.DataObjectAttribute()]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerDisplayAttribute("EK={EntityKey}, Email={Email}")]
    [System.ComponentModel.TypeConverterAttribute(typeof(CodeFluent.Runtime.Design.NameTypeConverter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CodeFluent.Runtime.CodeFluentRelationType))]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.mycie.com/contactmanager/contactmanager")]
    public partial class User : System.ICloneable, System.IComparable, System.IComparable<ContactManager.Proxy.User>, CodeFluent.Runtime.ICodeFluentMemberValidator, CodeFluent.Runtime.ICodeFluentSummaryValidator, CodeFluent.Runtime.ServiceModel.ICodeFluentCollectionEntity<string>, System.ComponentModel.IDataErrorInfo, System.IEquatable<ContactManager.Proxy.User>, CodeFluent.Runtime.Utilities.IKeyable<string>, CodeFluent.Runtime.Diagnostics.ITraceable, System.ComponentModel.INotifyPropertyChanged
    {
        
        private byte[] _rowVersion;
        
        private int _id = -1;
        
        private string _email = default(string);
        
        private string _firstName = default(string);
        
        private string _lastName = default(string);
        
        private string _fullName = default(string);
        
        [System.NonSerializedAttribute()]
        private CodeFluent.Runtime.BinaryServices.ServiceBinaryLargeObject _photo;
        
        [System.NonSerializedAttribute()]
        private MyCie.ContactManager.ContactCollection _contacts = default(MyCie.ContactManager.ContactCollection);
        
        private bool _raisePropertyChangedEvents = true;
        
        [System.NonSerializedAttribute()]
        private bool _isDeserializing;
        
        [System.NonSerializedAttribute()]
        private bool _isSerializing;
        
#if SILVERLIGHT
[System.Runtime.Serialization.DataMemberAttribute(Order=2147483647)]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
public CodeFluent.Runtime.CodeFluentEntityState _entityState;
#else
[System.Runtime.Serialization.DataMemberAttribute(Order=2147483647)]
private CodeFluent.Runtime.CodeFluentEntityState _entityState;
#endif
#if SILVERLIGHT
protected virtual void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
{
    if ((this.RaisePropertyChangedEvents == false))
    {
        return;
    }
    if ((this.PropertyChanged != null))
    {
        if ((System.Windows.Deployment.Current.Dispatcher.CheckAccess() == true))
        {
            this.PropertyChanged(this, e);
        }
        else
        {
            System.Windows.Deployment.Current.Dispatcher.BeginInvoke(this.PropertyChanged, this, e);
        }
    }
}
#else
protected virtual void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
{
    if ((this.RaisePropertyChangedEvents == false))
    {
        return;
    }
    if ((this.PropertyChanged != null))
    {
        this.PropertyChanged(this, e);
    }
}
#endif
        
        public User()
        {
            this._entityState = CodeFluent.Runtime.CodeFluentEntityState.Created;
        }
        
        string CodeFluent.Runtime.Utilities.IKeyable<System.String>.Key
        {
            get
            {
                return this.Email;
            }
        }
        
        [System.ComponentModel.BrowsableAttribute(false)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool RaisePropertyChangedEvents
        {
            get
            {
                return this._raisePropertyChangedEvents;
            }
            set
            {
                this._raisePropertyChangedEvents = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string EntityKey
        {
            get
            {
                return this.Id.ToString();
            }
            set
            {
                this.Id = ((int)(ConvertUtilities.ChangeType(value, typeof(int), -1)));
            }
        }
        
        public virtual string EntityDisplayName
        {
            get
            {
                return this.Email;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [System.ComponentModel.DataObjectFieldAttribute(false, true)]
        [System.ComponentModel.TypeConverterAttribute(typeof(CodeFluent.Runtime.Design.ByteArrayConverter))]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return this._rowVersion;
            }
            set
            {
                if (((value != null) 
                            && (value.Length == 0)))
                {
                    value = null;
                }
                this._rowVersion = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("RowVersion"));
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(((int)(-1)))]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false, Type=typeof(int))]
        [System.ComponentModel.DataObjectFieldAttribute(true)]
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=100)]
        public int Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Id"));
                this.BinaryLargeObjectsReset();
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(default(string))]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=200)]
        public string Email
        {
            get
            {
                return this._email;
            }
            set
            {
                if ((System.Collections.Generic.EqualityComparer<string>.Default.Equals(value, this._email) == true))
                {
                    return;
                }
                string oldKey = this._email;
                this._email = value;
                try
                {
                    this.OnCollectionKeyChanged(oldKey);
                }
                catch (System.ArgumentException )
                {
                    this._email = oldKey;
                    return;
                }
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Email"));
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(default(string))]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=300)]
        public string FirstName
        {
            get
            {
                return this._firstName;
            }
            set
            {
                this._firstName = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("FirstName"));
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(default(string))]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=400)]
        public string LastName
        {
            get
            {
                return this._lastName;
            }
            set
            {
                this._lastName = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("LastName"));
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(default(string))]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Type=typeof(string))]
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=500)]
        public string FullName
        {
            get
            {
                return this._fullName;
            }
            set
            {
                this._fullName = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("FullName"));
            }
        }
        
        public CodeFluent.Runtime.BinaryServices.ServiceBinaryLargeObject Photo
        {
            get
            {
                if ((this._photo == null))
                {
                    this._photo = new CodeFluent.Runtime.BinaryServices.ServiceBinaryLargeObject(CodeFluentContext.Get(MyCie.ContactManager.Proxy.Constants.MyCie_ContactManagerStoreName), this, "Photo", CodeFluent.Runtime.BinaryServices.BinaryLargeObjectMetaDatas.All, ContactManager.Proxy.User.WcfBinaryClient.Current.Channel);
                }
                return this._photo;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public MyCie.ContactManager.ContactCollection Contacts
        {
            get
            {
                return this._contacts;
            }
            set
            {
                this._contacts = value;
                this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Modified;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Contacts"));
            }
        }
        
        public virtual CodeFluent.Runtime.CodeFluentEntityState EntityState
        {
            get
            {
                return this._entityState;
            }
            set
            {
                if ((System.Collections.Generic.EqualityComparer<CodeFluent.Runtime.CodeFluentEntityState>.Default.Equals(value, this.EntityState) == true))
                {
                    return;
                }
                if (((this._entityState == CodeFluent.Runtime.CodeFluentEntityState.ToBeDeleted) 
                            && (value == CodeFluent.Runtime.CodeFluentEntityState.Modified)))
                {
                    return;
                }
                if (((this._entityState == CodeFluent.Runtime.CodeFluentEntityState.Created) 
                            && (value == CodeFluent.Runtime.CodeFluentEntityState.Modified)))
                {
                    return;
                }
                this._entityState = value;
                this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("EntityState"));
            }
        }
        
        public virtual bool IsDefaultEntityKey
        {
            get
            {
                if ((this.Id.Equals(-1) == true))
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
        }
        
        bool CodeFluent.Runtime.ServiceModel.ICodeFluentEntity.IsDefaultEntityKey
        {
            get
            {
                return this.IsDefaultEntityKey;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        protected virtual bool IsDeserializing
        {
            get
            {
                return this._isDeserializing;
            }
            set
            {
                this._isDeserializing = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        protected virtual bool IsSerializing
        {
            get
            {
                return this._isSerializing;
            }
            set
            {
                this._isSerializing = value;
            }
        }
        
        string System.ComponentModel.IDataErrorInfo.Error
        {
            get
            {
                return this.Validate(System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        string System.ComponentModel.IDataErrorInfo.this[string columnName]
        {
            get
            {
                return CodeFluentPersistence.ValidateMember(System.Globalization.CultureInfo.CurrentCulture, this, columnName, null);
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        public event System.EventHandler<CodeFluent.Runtime.ServiceModel.CodeFluentEntityActionEventArgs> EntityAction;
        
        public event System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<string>> KeyChanged;
        
        void CodeFluent.Runtime.ICodeFluentMemberValidator.Validate(System.Globalization.CultureInfo culture, string memberName, System.Collections.Generic.IList<CodeFluent.Runtime.CodeFluentValidationException> results)
        {
            this.ValidateMember(culture, memberName, results);
        }
        
        void CodeFluent.Runtime.ICodeFluentSummaryValidator.Validate(System.Globalization.CultureInfo culture, System.Collections.Generic.IList<CodeFluent.Runtime.CodeFluentValidationException> results)
        {
            this.ValidateLocal(culture, results);
        }
        
        protected virtual string ValidateLocal(System.Globalization.CultureInfo culture)
        {
            return CodeFluentPersistence.Validate(culture, this, null);
        }
        
        public virtual void ValidateLocal(System.Globalization.CultureInfo culture, System.Collections.Generic.IList<CodeFluent.Runtime.CodeFluentValidationException> results)
        {
            CodeFluent.Runtime.ServiceModel.CodeFluentEntityActionEventArgs evt = new CodeFluent.Runtime.ServiceModel.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Validating, true, results);
            evt.Culture = culture;
            this.OnEntityAction(evt);
            if ((evt.Cancel == true))
            {
                string externalValidate;
                if ((evt.Argument != null))
                {
                    externalValidate = evt.Argument.ToString();
                }
                else
                {
                    externalValidate = MyCie.ContactManager.Proxy.Resources.Manager.GetStringWithDefault(culture, "ContactManager.Proxy.User.ExternalValidate", "Type \'ContactManager.User\' cannot be validated.", null);
                }
                CodeFluentPersistence.AddValidationError(results, externalValidate);
            }
            CodeFluentPersistence.ValidateMember(culture, results, this, null);
            if ((this.Email == default(string)))
            {
                string localValidate = MyCie.ContactManager.Proxy.Resources.Manager.GetStringWithDefault(culture, "ContactManager.Proxy.User.Email.NullException", "\'Email\' property cannot be set to \'\' for type \'ContactManager.User\'", null);
                CodeFluentPersistence.AddValidationError(results, localValidate);
            }
            this.OnEntityAction(new CodeFluent.Runtime.ServiceModel.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.Validated, false, results));
        }
        
        public void Validate()
        {
            string var = this.Validate(System.Globalization.CultureInfo.CurrentCulture);
            if ((var != null))
            {
                throw new CodeFluent.Runtime.CodeFluentValidationException(var);
            }
        }
        
        string CodeFluent.Runtime.ICodeFluentValidator.Validate(System.Globalization.CultureInfo culture)
        {
            string localValidate = this.Validate(culture);
            return localValidate;
        }
        
        public virtual string Validate(System.Globalization.CultureInfo culture, CodeFluent.Runtime.ServiceModel.BindingFlags invokeFlags)
        {
            if ((((invokeFlags & CodeFluent.Runtime.ServiceModel.BindingFlags.Local) 
                        == 0) 
                        == false))
            {
                return this.ValidateLocal(culture);
            }
            if ((((invokeFlags & CodeFluent.Runtime.ServiceModel.BindingFlags.Remote) 
                        == 0) 
                        == false))
            {
                return this.ValidateRemote(culture);
            }
            return null;
        }
        
        public string Validate(System.Globalization.CultureInfo culture)
        {
            return this.Validate(culture, CodeFluent.Runtime.ServiceModel.BindingFlags.Local);
        }
        
        protected virtual string ValidateRemote(System.Globalization.CultureInfo culture)
        {
            if ((culture == null))
            {
                throw new System.ArgumentNullException("culture");
            }
            string ret = ContactManager.Proxy.User.WcfClient.Current.Channel.Validate(this, culture.Name);
            return ret;
        }
        
        public virtual bool Delete()
        {
            bool ret = ContactManager.Proxy.User.WcfClient.Current.Channel.DeleteByKey(this.Id);
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static ContactManager.Proxy.User Load(int id)
        {
            if ((id == -1))
            {
                return null;
            }
            ContactManager.Proxy.User ret = ContactManager.Proxy.User.WcfClient.Current.Channel.Load(id);
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, false)]
        public static ContactManager.Proxy.User LoadByEmail(string email)
        {
            ContactManager.Proxy.User ret = ContactManager.Proxy.User.WcfClient.Current.Channel.LoadByEmail(email);
            return ret;
        }
        
        public virtual bool SaveByValue()
        {
            if ((this.EntityState == CodeFluent.Runtime.CodeFluentEntityState.Unchanged))
            {
                return false;
            }
            this.Validate();
            bool ret = ContactManager.Proxy.User.WcfClient.Current.Channel.Save(this);
            return ret;
        }
        
        public virtual bool Save()
        {
            this.Validate();
            ContactManager.Proxy.User user = this;
            if ((ContactManager.Proxy.User.SaveByRef(ref user) == false))
            {
                return false;
            }
            user.CopyTo(this, true);
            this.RowVersion = user.RowVersion;
            this.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
            return true;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static ContactManager.Proxy.User LoadByEntityKey(string key)
        {
            if ((key == null))
            {
                throw new System.ArgumentNullException("key");
            }
            if ((key == string.Empty))
            {
                return null;
            }
            ContactManager.Proxy.User ret = ContactManager.Proxy.User.WcfClient.Current.Channel.LoadByEntityKey(key);
            return ret;
        }
        
        protected virtual void OnEntityAction(CodeFluent.Runtime.ServiceModel.CodeFluentEntityActionEventArgs e)
        {
            if ((this.EntityAction != null))
            {
                this.EntityAction(this, e);
            }
        }
        
        public virtual bool Reload(CodeFluent.Runtime.CodeFluentReloadOptions options)
        {
            ContactManager.Proxy.User user = ContactManager.Proxy.User.LoadByEntityKey(this.EntityKey);
            if ((user == null))
            {
                return false;
            }
            if ((((options & CodeFluent.Runtime.CodeFluentReloadOptions.Properties) 
                        == 0) 
                        == false))
            {
                user.CopyTo(this, true);
            }
            if ((((options & CodeFluent.Runtime.CodeFluentReloadOptions.RowVersion) 
                        == 0) 
                        == false))
            {
                this.RowVersion = user.RowVersion;
            }
            if ((((options & CodeFluent.Runtime.CodeFluentReloadOptions.BinaryLargeObjects) 
                        == 0) 
                        == false))
            {
                user.BinaryLargeObjectsCopyTo(this);
            }
            return true;
        }
        
        protected virtual void BinaryLargeObjectsCopyTo(ContactManager.Proxy.User user)
        {
            if ((user == null))
            {
                throw new System.ArgumentNullException("user");
            }
            if ((this._photo != null))
            {
                user._photo = this._photo;
            }
        }
        
        protected virtual void BinaryLargeObjectsReset()
        {
            if ((this._photo != null))
            {
                this._photo.ClearIdentifiersValues();
                this._photo.AddIdentifierValue(this.Id);
            }
        }
        
        public ContactManager.Proxy.User Clone(bool deep)
        {
            ContactManager.Proxy.User user = new ContactManager.Proxy.User();
            this.CopyTo(user, deep);
            return user;
        }
        
        public ContactManager.Proxy.User Clone()
        {
            ContactManager.Proxy.User localClone = this.Clone(true);
            return localClone;
        }
        
        object System.ICloneable.Clone()
        {
            object localClone = this.Clone();
            return localClone;
        }
        
        public virtual void CopyFrom(System.Collections.IDictionary dict, bool deep)
        {
            if ((dict == null))
            {
                throw new System.ArgumentNullException("dict");
            }
            if ((dict.Contains("Id") == true))
            {
                this.Id = ((int)(ConvertUtilities.ChangeType(dict["Id"], typeof(int), -1)));
            }
            if ((dict.Contains("Email") == true))
            {
                this.Email = ((string)(ConvertUtilities.ChangeType(dict["Email"], typeof(string), default(string))));
            }
            if ((dict.Contains("Contacts") == true))
            {
                this.Contacts = ((MyCie.ContactManager.ContactCollection)(ConvertUtilities.ChangeType(dict["Contacts"], typeof(MyCie.ContactManager.ContactCollection), default(MyCie.ContactManager.ContactCollection))));
            }
            if ((dict.Contains("FirstName") == true))
            {
                this.FirstName = ((string)(ConvertUtilities.ChangeType(dict["FirstName"], typeof(string), default(string))));
            }
            if ((dict.Contains("LastName") == true))
            {
                this.LastName = ((string)(ConvertUtilities.ChangeType(dict["LastName"], typeof(string), default(string))));
            }
            if ((dict.Contains("Photo") == true))
            {
                this.Photo.SavePostedFile(dict["Photo"]);
            }
            this.OnEntityAction(new CodeFluent.Runtime.ServiceModel.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.CopyFrom, false, dict));
        }
        
        public virtual void CopyTo(ContactManager.Proxy.User user, bool deep)
        {
            if ((user == null))
            {
                throw new System.ArgumentNullException("user");
            }
            user.Id = this.Id;
            user.Email = this.Email;
            user.Contacts = this.Contacts;
            user.FirstName = this.FirstName;
            user.LastName = this.LastName;
            user._photo = this._photo;
            this.OnEntityAction(new CodeFluent.Runtime.ServiceModel.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.CopyTo, false, user));
        }
        
        public virtual void CopyTo(System.Collections.IDictionary dict, bool deep)
        {
            if ((dict == null))
            {
                throw new System.ArgumentNullException("dict");
            }
            dict["Id"] = this.Id;
            dict["Email"] = this.Email;
            dict["Contacts"] = this.Contacts;
            dict["FirstName"] = this.FirstName;
            dict["LastName"] = this.LastName;
            dict["Photo"] = this.Photo;
            this.OnEntityAction(new CodeFluent.Runtime.ServiceModel.CodeFluentEntityActionEventArgs(this, CodeFluent.Runtime.CodeFluentEntityAction.CopyTo, false, dict));
        }
        
        int System.IComparable.CompareTo(object value)
        {
            ContactManager.Proxy.User user = null;
user = value as ContactManager.Proxy.User;
            if ((user == null))
            {
                throw new System.ArgumentException("value");
            }
            int localCompareTo = this.CompareTo(user);
            return localCompareTo;
        }
        
        public virtual int CompareTo(ContactManager.Proxy.User user)
        {
            if ((user == null))
            {
                throw new System.ArgumentNullException("user");
            }
            int localCompareTo = this.Email.CompareTo(user.Email);
            return localCompareTo;
        }
        
        public virtual bool Equals(ContactManager.Proxy.User user)
        {
            if ((user == null))
            {
                return false;
            }
            if ((this.Id == -1))
            {
                return base.Equals(user);
            }
            return (this.Id.Equals(user.Id) == true);
        }
        
        public override int GetHashCode()
        {
            return this._id;
        }
        
        public override bool Equals(object obj)
        {
            ContactManager.Proxy.User user = null;
user = obj as ContactManager.Proxy.User;
            return this.Equals(user);
        }
        
        public string Trace()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            System.IO.StringWriter stringWriter = new System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture);
            System.CodeDom.Compiler.IndentedTextWriter writer = new System.CodeDom.Compiler.IndentedTextWriter(stringWriter);
            this.BaseTrace(writer);
            writer.Flush();
            ((System.IDisposable)(writer)).Dispose();
            ((System.IDisposable)(stringWriter)).Dispose();
            string sr = stringBuilder.ToString();
            return sr;
        }
        
        void CodeFluent.Runtime.Diagnostics.ITraceable.Trace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            this.BaseTrace(writer);
        }
        
        protected virtual void BaseTrace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            writer.Write("[");
            writer.Write("Id=");
            writer.Write(this.Id);
            writer.Write(",");
            writer.Write("Email=");
            writer.Write(this.Email);
            writer.Write(",");
            writer.Write("FirstName=");
            writer.Write(this.FirstName);
            writer.Write(",");
            writer.Write("LastName=");
            writer.Write(this.LastName);
            writer.Write(",");
            writer.Write("FullName=");
            writer.Write(this.FullName);
            writer.Write(",");
            writer.Write("Photo=");
            ((CodeFluent.Runtime.Diagnostics.ITraceable)(this.Photo)).Trace(writer);
            writer.Write(",");
            writer.Write("Contacts=");
            writer.Write(this.Contacts);
            writer.Write(", EntityState=");
            writer.Write(this.EntityState);
            writer.Write("]");
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)]
        public static bool Save(ContactManager.Proxy.User user)
        {
            if ((user == null))
            {
                return false;
            }
            return user.Save();
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)]
        public static bool Delete(ContactManager.Proxy.User user)
        {
            if ((user == null))
            {
                return false;
            }
            return user.Delete();
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)]
        public static bool Insert(ContactManager.Proxy.User user)
        {
            if ((user == null))
            {
                return false;
            }
            return user.Save();
        }
        
        [System.Runtime.Serialization.OnDeserializingAttribute()]
        protected internal void OnEntityDeserializing(System.Runtime.Serialization.StreamingContext context)
        {
            this.IsDeserializing = true;
            this._id = -1;
            this._email = default(string);
            this._firstName = default(string);
            this._lastName = default(string);
            this._fullName = default(string);
            this._contacts = default(MyCie.ContactManager.ContactCollection);
            this._raisePropertyChangedEvents = true;
            this._entityState = CodeFluent.Runtime.CodeFluentEntityState.Created;
            this._raisePropertyChangedEvents = true;
        }
        
        [System.Runtime.Serialization.OnDeserializedAttribute()]
        protected internal void OnEntityDeserialized(System.Runtime.Serialization.StreamingContext context)
        {
            this.IsDeserializing = false;
        }
        
        [System.Runtime.Serialization.OnSerializedAttribute()]
        protected internal void OnEntitySerialized(System.Runtime.Serialization.StreamingContext context)
        {
            this.IsSerializing = false;
        }
        
        [System.Runtime.Serialization.OnSerializingAttribute()]
        protected internal void OnEntitySerializing(System.Runtime.Serialization.StreamingContext context)
        {
            this.IsSerializing = true;
        }
        
        public static bool SaveByRef(ref ContactManager.Proxy.User user)
        {
            if ((user == null))
            {
                return false;
            }
            if ((user.EntityState == CodeFluent.Runtime.CodeFluentEntityState.Unchanged))
            {
                return false;
            }
            bool ret = ContactManager.Proxy.User.WcfClient.Current.Channel.SaveByRef(ref user);
            return ret;
        }
        
        protected virtual void ValidateMember(System.Globalization.CultureInfo culture, string memberName, System.Collections.Generic.IList<CodeFluent.Runtime.CodeFluentValidationException> results)
        {
        }
        
        protected void OnCollectionKeyChanged(string key)
        {
            if ((this.KeyChanged != null))
            {
                this.KeyChanged(this, new CodeFluent.Runtime.Utilities.KeyChangedEventArgs<string>(key));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.61214.0762")]
        public partial class WcfClient : CodeFluent.Runtime.ServiceModel.CodeFluentClient<ContactManager.Proxy.IUserService>, CodeFluent.Runtime.ServiceModel.ISafeClosable
        {
            
            private static ContactManager.Proxy.User.WcfClient _current = new ContactManager.Proxy.User.WcfClient();
            
            public new ContactManager.Proxy.IUserService Channel
            {
                get
                {
                    return base.Channel;
                }
            }
            
            public static ContactManager.Proxy.User.WcfClient Current
            {
                get
                {
                    return WcfClient._current;
                }
            }
            
            public virtual void SafeClose()
            {
                CodeFluent.Runtime.ServiceModel.ServiceModelUtilities.SafeClose<ContactManager.Proxy.IUserService>(this);
            }
            
            void CodeFluent.Runtime.ServiceModel.ISafeClosable.SafeClose()
            {
                this.SafeClose();
            }
            
            public static void Reset()
            {
                if ((WcfClient._current != null))
                {
                    WcfClient._current.SafeClose();
                }
                WcfClient._current = new ContactManager.Proxy.User.WcfClient();
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.61214.0762")]
        public partial class WcfBinaryClient : CodeFluent.Runtime.ServiceModel.CodeFluentClient<CodeFluent.Runtime.BinaryServices.ICodeFluentBinaryService>, CodeFluent.Runtime.ServiceModel.ISafeClosable
        {
            
            private static ContactManager.Proxy.User.WcfBinaryClient _current = new ContactManager.Proxy.User.WcfBinaryClient();
            
            public WcfBinaryClient() : 
                    base("ContactManager.User/BinaryService")
            {
            }
            
            public new CodeFluent.Runtime.BinaryServices.ICodeFluentBinaryService Channel
            {
                get
                {
                    return base.Channel;
                }
            }
            
            public static ContactManager.Proxy.User.WcfBinaryClient Current
            {
                get
                {
                    return ContactManager.Proxy.User.WcfBinaryClient._current;
                }
            }
            
            public virtual void SafeClose()
            {
                CodeFluent.Runtime.ServiceModel.ServiceModelUtilities.SafeClose<CodeFluent.Runtime.BinaryServices.ICodeFluentBinaryService>(this);
            }
            
            void CodeFluent.Runtime.ServiceModel.ISafeClosable.SafeClose()
            {
                this.SafeClose();
            }
            
            public static void Reset()
            {
                if ((WcfBinaryClient._current != null))
                {
                    WcfBinaryClient._current.SafeClose();
                }
                WcfBinaryClient._current = new ContactManager.Proxy.User.WcfBinaryClient();
            }
        }
    }
}
