//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftFluent.SqlServerInMemory
{
    using CodeFluent.Runtime;
    using CodeFluent.Runtime.Utilities;
    
    
    // CodeFluent Entities generated (http://www.softfluent.com). Date: Wednesday, 09 July 2014 12:19.
    // Build:1.0.61214.0772
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.61214.0772")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DataObjectAttribute()]
    [System.Diagnostics.DebuggerDisplayAttribute("Count={Count}")]
    [System.ComponentModel.TypeConverterAttribute(typeof(CodeFluent.Runtime.Design.CollectionTypeConverter))]
    public partial class ContactSourceCollection : System.Collections.IList, System.Collections.ICollection, CodeFluent.Runtime.ICodeFluentSet, System.Collections.Generic.IList<SoftFluent.SqlServerInMemory.ContactSource>, System.Collections.Generic.ICollection<SoftFluent.SqlServerInMemory.ContactSource>, System.ComponentModel.IRaiseItemChangedEvents, System.ICloneable, System.ComponentModel.INotifyPropertyChanged, System.Collections.Specialized.INotifyCollectionChanged, System.ComponentModel.IBindingList, System.ComponentModel.ICancelAddNew
    {
        
        private bool _raisePropertyChangedEvents = true;
        
        private bool _raiseCollectionChangedEvents = true;
        
        [System.NonSerializedAttribute()]
        private System.Collections.Generic.List<SoftFluent.SqlServerInMemory.ContactSource> _baseList = new System.Collections.Generic.List<SoftFluent.SqlServerInMemory.ContactSource>();
        
        [System.NonSerializedAttribute()]
        private System.Collections.Generic.Dictionary<int, SoftFluent.SqlServerInMemory.ContactSource> _baseTable = new System.Collections.Generic.Dictionary<int, SoftFluent.SqlServerInMemory.ContactSource>();
        
        [System.NonSerializedAttribute()]
        private System.Collections.Hashtable _relations = new System.Collections.Hashtable();
        
        private int _maxCount = 2147483647;
        
        [System.NonSerializedAttribute()]
        private int _addNewPos = -1;
        
        [System.NonSerializedAttribute()]
        private CodeFluent.Runtime.Utilities.BindingListManager<SoftFluent.SqlServerInMemory.ContactSource> _blm3365826304;
        
        private bool _raiseListChangedEvents = true;
        
        private System.Collections.Specialized.NotifyCollectionChangedEventHandler _h2943838991;

        event System.Collections.Specialized.NotifyCollectionChangedEventHandler System.Collections.Specialized.INotifyCollectionChanged.CollectionChanged{add{_h2943838991+=value;}remove{_h2943838991-=value;}}
        
        public ContactSourceCollection()
        {
            this._blm3365826304 = new CodeFluent.Runtime.Utilities.BindingListManager<SoftFluent.SqlServerInMemory.ContactSource>(this);
        }
        
        [System.ComponentModel.BrowsableAttribute(false)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public virtual bool RaisePropertyChangedEvents
        {
            get
            {
                return this._raisePropertyChangedEvents;
            }
            set
            {
                this._raisePropertyChangedEvents = value;
            }
        }
        
        public virtual bool RaiseCollectionChangedEvents
        {
            get
            {
                return this._raiseCollectionChangedEvents;
            }
            set
            {
                this._raiseCollectionChangedEvents = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        protected System.Collections.Generic.List<SoftFluent.SqlServerInMemory.ContactSource> BaseList
        {
            get
            {
                return this._baseList;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        protected System.Collections.Generic.Dictionary<int, SoftFluent.SqlServerInMemory.ContactSource> BaseTable
        {
            get
            {
                return this._baseTable;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        System.Collections.IDictionary CodeFluent.Runtime.ICodeFluentSet.Relations
        {
            get
            {
                return this._relations;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public virtual int MaxCount
        {
            get
            {
                return this._maxCount;
            }
            set
            {
                this._maxCount = value;
            }
        }
        
        public SoftFluent.SqlServerInMemory.ContactSource this[int index]
        {
            get
            {
                return ((SoftFluent.SqlServerInMemory.ContactSource)(this.BaseList[index]));
            }
            set
            {
                this.BaseList[index] = value;
            }
        }
        
        object System.Collections.IList.this[int index]
        {
            get
            {
                object i = this.BaseList[index];
                return i;
            }
            set
            {
                this.BaseList[index] = ((SoftFluent.SqlServerInMemory.ContactSource)(value));
            }
        }
        
        public virtual int Count
        {
            get
            {
                int v = ((System.Collections.IList)(this.BaseList)).Count;
                return v;
            }
        }
        
        public virtual bool IsSynchronized
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsSynchronized;
                return v;
            }
        }
        
        public virtual object SyncRoot
        {
            get
            {
                object v = ((System.Collections.IList)(this.BaseList)).SyncRoot;
                return v;
            }
        }
        
        public virtual bool IsFixedSize
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsFixedSize;
                return v;
            }
        }
        
        public virtual bool IsReadOnly
        {
            get
            {
                bool v = ((System.Collections.IList)(this.BaseList)).IsReadOnly;
                return v;
            }
        }
        
        public virtual bool RaiseListChangedEvents
        {
            get
            {
                return this._raiseListChangedEvents;
            }
            set
            {
                this._raiseListChangedEvents = value;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowEdit
        {
            get
            {
                return this._blm3365826304.AllowEdit;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowNew
        {
            get
            {
                return this._blm3365826304.AllowNew;
            }
        }
        
        bool System.ComponentModel.IBindingList.AllowRemove
        {
            get
            {
                return this._blm3365826304.AllowRemove;
            }
        }
        
        bool System.ComponentModel.IBindingList.IsSorted
        {
            get
            {
                return this._blm3365826304.IsSorted;
            }
        }
        
        System.ComponentModel.ListSortDirection System.ComponentModel.IBindingList.SortDirection
        {
            get
            {
                return this._blm3365826304.SortDirection;
            }
        }
        
        System.ComponentModel.PropertyDescriptor System.ComponentModel.IBindingList.SortProperty
        {
            get
            {
                return this._blm3365826304.SortProperty;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsChangeNotification
        {
            get
            {
                return true;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsSearching
        {
            get
            {
                return this._blm3365826304.SupportsSearching;
            }
        }
        
        bool System.ComponentModel.IBindingList.SupportsSorting
        {
            get
            {
                return this._blm3365826304.SupportsSorting;
            }
        }
        
        bool System.ComponentModel.IRaiseItemChangedEvents.RaisesItemChangedEvents
        {
            get
            {
                return this.RaiseListChangedEvents;
            }
        }
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.CollectionChangeEventHandler CollectionChanged;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.AddingNewEventHandler AddingNew;
        
        [field:System.NonSerializedAttribute()]
        public event System.ComponentModel.ListChangedEventHandler ListChanged;
        
        protected virtual void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
        {
            if ((this.RaisePropertyChangedEvents == false))
            {
                return;
            }
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, e);
            }
        }
        
        protected virtual void OnCollectionChanged(System.ComponentModel.CollectionChangeEventArgs e)
        {
            if ((this.RaiseCollectionChangedEvents == false))
            {
                return;
            }
            if ((this.CollectionChanged != null))
            {
                this.CollectionChanged(this, e);
            }
            CodeFluent.Runtime.ServiceModel.CollectionChangeNotifier.Notify(this, e, this._h2943838991);
            this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Count"));
            this.OnPropertyChanged(new System.ComponentModel.PropertyChangedEventArgs("Item[]"));
        }
        
        protected virtual void Relate(SoftFluent.SqlServerInMemory.ContactSource item, CodeFluent.Runtime.CodeFluentRelationType relationType)
        {
            ((CodeFluent.Runtime.ICodeFluentSet)(this)).Relations[item] = relationType;
        }
        
        public int Add(SoftFluent.SqlServerInMemory.ContactSource contactSource)
        {
            int localAdd = this.BaseList.Count;
            this.BaseAdd(contactSource);
            return localAdd;
        }
        
        protected virtual int BaseAdd(SoftFluent.SqlServerInMemory.ContactSource contactSource)
        {
            if ((contactSource == null))
            {
                throw new System.ArgumentNullException("contactSource");
            }
            if ((contactSource.Id == -1))
            {
                CodeFluent.Runtime.CodeFluentRuntimeException.Throw("invalidEntityKey", "Id", "contactSource", "SoftFluent.SqlServerInMemory.ContactSource");
            }
            try
            {
                this.BaseTable.Add(contactSource.Id, contactSource);
            }
            catch (System.ArgumentNullException ane)
            {
                throw new System.ArgumentNullException(SoftFluent.SqlServerInMemory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "SoftFluent.SqlServerInMemory.ContactSourceCollection", contactSource.EntityKey), ane);
            }
            catch (System.ArgumentException ae)
            {
                throw new System.ArgumentException(SoftFluent.SqlServerInMemory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "SoftFluent.SqlServerInMemory.ContactSourceCollection", contactSource.Id), ae);
            }
            contactSource.KeyChanged += new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<int>>(this.OnItemKeyChanged);
            int localAdd = this.BaseList.Count;
            this.BaseList.Add(contactSource);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Add, contactSource, localAdd));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemAdded, localAdd));
            return localAdd;
        }
        
        int System.Collections.IList.Add(object value)
        {
            SoftFluent.SqlServerInMemory.ContactSource contactSource = null;
            try
            {
                contactSource = ((SoftFluent.SqlServerInMemory.ContactSource)(value));
            }
            catch (System.InvalidCastException )
            {
                string key = null;
                try
                {
                    key = ((string)(value));
                    int count = this.Count;
                    if ((this.AddByEntityKey(key) != null))
                    {
                        return 1;
                    }
                    return 0;
                }
                catch (System.InvalidCastException )
                {
                }
                if ((key == null))
                {
                    throw new System.ArgumentException("value");
                }
            }
            if ((contactSource == null))
            {
                throw new System.ArgumentException("value");
            }
            int localAdd = this.Add(contactSource);
            return localAdd;
        }
        
        void System.Collections.Generic.ICollection<SoftFluent.SqlServerInMemory.ContactSource>.Add(SoftFluent.SqlServerInMemory.ContactSource contactSource)
        {
            this.BaseAdd(contactSource);
        }
        
        public virtual SoftFluent.SqlServerInMemory.ContactSource AddByEntityKey(string key)
        {
            SoftFluent.SqlServerInMemory.ContactSource contactSource = SoftFluent.SqlServerInMemory.ContactSource.LoadByEntityKey(key);
            if (((contactSource != null) 
                        && (this.Contains(contactSource) == false)))
            {
                this.Add(contactSource);
            }
            return contactSource;
        }
        
        public void Sort()
        {
            this.Sort(null);
        }
        
        public virtual void Sort(System.Collections.Generic.IComparer<SoftFluent.SqlServerInMemory.ContactSource> comparer)
        {
            this.BaseList.Sort(comparer);
        }
        
        public void CopyTo(SoftFluent.SqlServerInMemory.ContactSource[] array, int index)
        {
            this.BaseCopyTo(array, index);
        }
        
        protected virtual void BaseCopyTo(SoftFluent.SqlServerInMemory.ContactSource[] array, int index)
        {
            this.BaseList.CopyTo(array, index);
        }
        
        void System.Collections.ICollection.CopyTo(System.Array array, int index)
        {
            CodeFluent.Runtime.Utilities.ConvertUtilities.CopyTo(this, array, index);
        }
        
        public bool Contains(SoftFluent.SqlServerInMemory.ContactSource contactSource)
        {
            bool localContains = this.BaseContains(contactSource);
            return localContains;
        }
        
        protected virtual bool BaseContains(SoftFluent.SqlServerInMemory.ContactSource contactSource)
        {
            if ((contactSource == null))
            {
                return false;
            }
            bool localContains = this.BaseTable.ContainsKey(contactSource.Id);
            return localContains;
        }
        
        bool System.Collections.IList.Contains(object value)
        {
            SoftFluent.SqlServerInMemory.ContactSource contactSource;
			contactSource = value as SoftFluent.SqlServerInMemory.ContactSource;
            return this.Contains(contactSource);
        }
        
        public int IndexOf(SoftFluent.SqlServerInMemory.ContactSource contactSource)
        {
            int localIndexOf = this.BaseIndexOf(contactSource);
            return localIndexOf;
        }
        
        protected virtual int BaseIndexOf(SoftFluent.SqlServerInMemory.ContactSource contactSource)
        {
            if ((contactSource == null))
            {
                return -1;
            }
            int localIndexOf = this.BaseList.IndexOf(contactSource);
            return localIndexOf;
        }
        
        int System.Collections.IList.IndexOf(object value)
        {
            SoftFluent.SqlServerInMemory.ContactSource contactSource;
			contactSource = value as SoftFluent.SqlServerInMemory.ContactSource;
            return this.IndexOf(contactSource);
        }
        
        public void Insert(int index, SoftFluent.SqlServerInMemory.ContactSource contactSource)
        {
            this.BaseInsert(index, contactSource);
        }
        
        protected virtual void BaseInsert(int index, SoftFluent.SqlServerInMemory.ContactSource contactSource)
        {
            if ((contactSource == null))
            {
                throw new System.ArgumentNullException("contactSource");
            }
            try
            {
                this.BaseTable.Add(contactSource.Id, contactSource);
            }
            catch (System.ArgumentNullException ane)
            {
                throw new System.ArgumentNullException(SoftFluent.SqlServerInMemory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "SoftFluent.SqlServerInMemory.ContactSourceCollection", contactSource.EntityKey), ane);
            }
            catch (System.ArgumentException ae)
            {
                throw new System.ArgumentException(SoftFluent.SqlServerInMemory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "SoftFluent.SqlServerInMemory.ContactSourceCollection", contactSource.Id), ae);
            }
            this.BaseList.Insert(index, contactSource);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Add, contactSource, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemAdded, index));
        }
        
        void System.Collections.IList.Insert(int index, object value)
        {
            SoftFluent.SqlServerInMemory.ContactSource contactSource;
			contactSource = value as SoftFluent.SqlServerInMemory.ContactSource;
            this.Insert(index, contactSource);
        }
        
        public virtual void Clear()
        {
            int index;
            int count = this.Count;
            for (index = 0; (index < count); index = (index + 1))
            {
                SoftFluent.SqlServerInMemory.ContactSource ContactSource = this[0];
                this.BaseRemove(ContactSource);
            }
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Refresh, null));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.Reset, -1));
        }
        
        public bool Remove(SoftFluent.SqlServerInMemory.ContactSource contactSource)
        {
            return this.BaseRemove(contactSource);
        }
        
        protected virtual bool BaseRemove(SoftFluent.SqlServerInMemory.ContactSource contactSource)
        {
            if ((contactSource == null))
            {
                throw new System.ArgumentNullException("contactSource");
            }
            int index = this.IndexOf(contactSource);
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(((System.ComponentModel.ListChangedType)(CodeFluent.Runtime.Utilities.SortableBindingList<SoftFluent.SqlServerInMemory.ContactSource>.ListChangedTypeDeleting)), index));
            bool ret;
            ret = this.BaseList.Remove(contactSource);
            contactSource.KeyChanged -= new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<int>>(this.OnItemKeyChanged);
            ret = this.BaseTable.Remove(contactSource.Id);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Remove, contactSource, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemDeleted, index));
            return ret;
        }
        
        void System.Collections.IList.Remove(object value)
        {
            SoftFluent.SqlServerInMemory.ContactSource contactSource;
			contactSource = value as SoftFluent.SqlServerInMemory.ContactSource;
            this.Remove(contactSource);
        }
        
        public virtual void RemoveAt(int index)
        {
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(((System.ComponentModel.ListChangedType)(CodeFluent.Runtime.Utilities.SortableBindingList<SoftFluent.SqlServerInMemory.ContactSource>.ListChangedTypeDeleting)), index));
            SoftFluent.SqlServerInMemory.ContactSource contactSource = this.BaseList[index];
            if ((contactSource != null))
            {
                contactSource.KeyChanged -= new System.EventHandler<CodeFluent.Runtime.Utilities.KeyChangedEventArgs<int>>(this.OnItemKeyChanged);
                this.BaseTable.Remove(contactSource.Id);
            }
            this.BaseList.RemoveAt(index);
            this.OnCollectionChanged(new CodeFluent.Runtime.Utilities.IndexedCollectionChangeEventArgs(System.ComponentModel.CollectionChangeAction.Remove, contactSource, index));
            this.OnListChanged(new System.ComponentModel.ListChangedEventArgs(System.ComponentModel.ListChangedType.ItemDeleted, index));
        }
        
        public virtual System.Collections.Generic.IEnumerator<SoftFluent.SqlServerInMemory.ContactSource> GetEnumerator()
        {
            System.Collections.Generic.IEnumerator<SoftFluent.SqlServerInMemory.ContactSource> e = this.BaseList.GetEnumerator();
            return e;
        }
        
        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return this.BaseList.GetEnumerator();
        }
        
        private SoftFluent.SqlServerInMemory.ContactSource TryGetValue(int key)
        {
            SoftFluent.SqlServerInMemory.ContactSource contactSource;
            if ((this.BaseTable.TryGetValue(key, out contactSource) == true))
            {
                return contactSource;
            }
            return null;
        }
        
        public void SetItem(int id, SoftFluent.SqlServerInMemory.ContactSource value)
        {
            if ((id == -1))
            {
                throw new System.ArgumentNullException("id");
            }
            if ((value == null))
            {
                SoftFluent.SqlServerInMemory.ContactSource contactSource = this.TryGetValue(id);
                if ((contactSource != null))
                {
                    this.Remove(contactSource);
                }
                return;
            }
            this.BaseTable[value.Id] = value;
        }
        
        public SoftFluent.SqlServerInMemory.ContactSource GetItem(int id)
        {
            if ((id == -1))
            {
                throw new System.ArgumentNullException("id");
            }
            SoftFluent.SqlServerInMemory.ContactSource i = this.TryGetValue(id);
            return i;
        }
        
        public virtual void SaveAll()
        {
            int index;
            for (index = (this.Count - 1); (index >= 0); index = (index - 1))
            {
                SoftFluent.SqlServerInMemory.ContactSource contactSource = this[index];
                contactSource.Save();
                if ((contactSource.EntityState == CodeFluent.Runtime.CodeFluentEntityState.Deleted))
                {
                    this.Remove(contactSource);
                }
            }
        }
        
        private void LoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions, System.Data.IDataReader reader)
        {
            if ((reader == null))
            {
                throw new System.ArgumentNullException("reader");
            }
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            this.BaseList.Clear();
            this.BaseTable.Clear();
            int count = 0;
            int readCount = 0;
            bool readerRead;
            for (readerRead = reader.Read(); ((readerRead == true) 
                        && ((count < this.MaxCount) 
                        && (count < pageSize))); readerRead = reader.Read())
            {
                readCount = (readCount + 1);
                if ((CodeFluent.Runtime.CodeFluentPersistence.CanAddEntity(pageIndex, pageSize, pageOptions, readCount) == true))
                {
                    SoftFluent.SqlServerInMemory.ContactSource contactSource = new SoftFluent.SqlServerInMemory.ContactSource();
                    ((CodeFluent.Runtime.ICodeFluentEntity)(contactSource)).ReadRecord(reader);
                    if ((this.BaseContains(contactSource) == false))
                    {
                        this.BaseAdd(contactSource);
                        count = (count + 1);
                    }
                    contactSource.EntityState = CodeFluent.Runtime.CodeFluentEntityState.Unchanged;
                }
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static SoftFluent.SqlServerInMemory.ContactSourceCollection PageLoadAll(int pageIndex, int pageSize, CodeFluent.Runtime.PageOptions pageOptions)
        {
            if ((pageIndex < 0))
            {
                pageIndex = 0;
            }
            if ((pageSize < 0))
            {
                if ((pageOptions != null))
                {
                    pageSize = pageOptions.DefaultPageSize;
                }
                else
                {
                    pageSize = int.MaxValue;
                }
            }
            SoftFluent.SqlServerInMemory.ContactSourceCollection ret = new SoftFluent.SqlServerInMemory.ContactSourceCollection();
            System.Data.IDataReader reader = null;
            try
            {
                reader = SoftFluent.SqlServerInMemory.ContactSourceCollection.PageDataLoadAll(pageOptions);
                if ((reader == null))
                {
                    return ret;
                }
                ret.LoadAll(pageIndex, pageSize, pageOptions, reader);
            }
            finally
            {
                if ((reader != null))
                {
                    reader.Dispose();
                }
                CodeFluent.Runtime.CodeFluentPersistence.CompleteCommand(SoftFluent.SqlServerInMemory.Constants.SoftFluent_SqlServerInMemoryStoreName);
            }
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static SoftFluent.SqlServerInMemory.ContactSourceCollection LoadAll()
        {
            SoftFluent.SqlServerInMemory.ContactSourceCollection ret = SoftFluent.SqlServerInMemory.ContactSourceCollection.PageLoadAll(int.MinValue, int.MaxValue, null);
            return ret;
        }
        
        public static System.Data.IDataReader PageDataLoadAll(CodeFluent.Runtime.PageOptions pageOptions)
        {
            CodeFluent.Runtime.CodeFluentPersistence persistence = CodeFluentContext.Get(SoftFluent.SqlServerInMemory.Constants.SoftFluent_SqlServerInMemoryStoreName).Persistence;
            persistence.CreateStoredProcedureCommand(null, "ContactSource", "LoadAll");
            if ((pageOptions != null))
            {
                System.Collections.IEnumerator enumerator = pageOptions.OrderByArguments.GetEnumerator();
                bool b;
                int index = 0;
                for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
                {
                    CodeFluent.Runtime.OrderByArgument argument = ((CodeFluent.Runtime.OrderByArgument)(enumerator.Current));
                    persistence.AddParameter(string.Format("@_orderBy{0}", index), argument.Name);
                    persistence.AddParameter(string.Format("@_orderByDirection{0}", index), ((int)(argument.Direction)));
                    index = (index + 1);
                }
            }
            System.Data.IDataReader reader = CodeFluentContext.Get(SoftFluent.SqlServerInMemory.Constants.SoftFluent_SqlServerInMemoryStoreName).Persistence.ExecuteReader();
            return reader;
        }
        
        public static System.Data.IDataReader DataLoadAll()
        {
            System.Data.IDataReader reader = SoftFluent.SqlServerInMemory.ContactSourceCollection.PageDataLoadAll(null);
            return reader;
        }
        
        protected virtual void BaseTrace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            writer.Write("[");
            writer.Write(string.Concat("Count=", this.Count));
            writer.Write("]");
        }
        
        public string Trace()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            System.IO.StringWriter stringWriter = new System.IO.StringWriter(stringBuilder, System.Globalization.CultureInfo.CurrentCulture);
            System.CodeDom.Compiler.IndentedTextWriter writer = new System.CodeDom.Compiler.IndentedTextWriter(stringWriter);
            this.BaseTrace(writer);
            writer.Flush();
            ((System.IDisposable)(writer)).Dispose();
            ((System.IDisposable)(stringWriter)).Dispose();
            string sr = stringBuilder.ToString();
            return sr;
        }
        
        void CodeFluent.Runtime.ICodeFluentObject.Trace(System.CodeDom.Compiler.IndentedTextWriter writer)
        {
            this.BaseTrace(writer);
        }
        
        public virtual void CopyTo(SoftFluent.SqlServerInMemory.ContactSourceCollection collection, bool deep)
        {
            if ((typeof(System.ICloneable).IsAssignableFrom(typeof(SoftFluent.SqlServerInMemory.ContactSource)) == false))
            {
                deep = false;
            }
            System.Collections.Generic.IEnumerator<SoftFluent.SqlServerInMemory.ContactSource> enumerator = this.GetEnumerator();
            bool b;
            for (b = enumerator.MoveNext(); b; b = enumerator.MoveNext())
            {
                if ((deep == true))
                {
                    collection.Add(((SoftFluent.SqlServerInMemory.ContactSource)(((System.ICloneable)(enumerator.Current)).Clone())));
                }
                else
                {
                    collection.Add(enumerator.Current);
                }
            }
        }
        
        public virtual SoftFluent.SqlServerInMemory.ContactSourceCollection Clone(bool deep)
        {
            SoftFluent.SqlServerInMemory.ContactSourceCollection ret = new SoftFluent.SqlServerInMemory.ContactSourceCollection();
            this.CopyTo(ret, deep);
            return ret;
        }
        
        object System.ICloneable.Clone()
        {
            return this.Clone(true);
        }
        
        public virtual void CancelNew(int index)
        {
            if (((this._addNewPos >= 0) 
                        && (this._addNewPos == index)))
            {
                this.RemoveAt(index);
                this._addNewPos = -1;
            }
        }
        
        public virtual void EndNew(int index)
        {
            if (((this._addNewPos >= 0) 
                        && (this._addNewPos == index)))
            {
                this._addNewPos = -1;
            }
        }
        
        void System.ComponentModel.IBindingList.AddIndex(System.ComponentModel.PropertyDescriptor property)
        {
            this._blm3365826304.AddIndex(property);
        }
        
        protected virtual void OnAddingNew(System.ComponentModel.AddingNewEventArgs e)
        {
            if ((this.AddingNew != null))
            {
                this.AddingNew(this, e);
            }
        }
        
        object System.ComponentModel.IBindingList.AddNew()
        {
            SoftFluent.SqlServerInMemory.ContactSource add = new SoftFluent.SqlServerInMemory.ContactSource();
            System.ComponentModel.AddingNewEventArgs e = new System.ComponentModel.AddingNewEventArgs(add);
            this.OnAddingNew(e);
            add = ((SoftFluent.SqlServerInMemory.ContactSource)(e.NewObject));
            if ((add == null))
            {
                add = new SoftFluent.SqlServerInMemory.ContactSource();
            }
            add.Id = 0;
            this._addNewPos = this.Add(add);
            return add;
        }
        
        void System.ComponentModel.IBindingList.ApplySort(System.ComponentModel.PropertyDescriptor property, System.ComponentModel.ListSortDirection direction)
        {
            this._blm3365826304.ApplySort(property, direction);
        }
        
        int System.ComponentModel.IBindingList.Find(System.ComponentModel.PropertyDescriptor property, object key)
        {
            return this._blm3365826304.Find(property, key);
        }
        
        void System.ComponentModel.IBindingList.RemoveIndex(System.ComponentModel.PropertyDescriptor property)
        {
            this._blm3365826304.RemoveIndex(property);
        }
        
        void System.ComponentModel.IBindingList.RemoveSort()
        {
            this._blm3365826304.RemoveSort();
        }
        
        protected virtual void OnListChanged(System.ComponentModel.ListChangedEventArgs e)
        {
            if ((e == null))
            {
                throw new System.ArgumentNullException("e");
            }
            if ((this.RaiseListChangedEvents == false))
            {
                return;
            }
            if ((((e.ListChangedType == System.ComponentModel.ListChangedType.Reset) 
                        == false) 
                        && (e.NewIndex < 0)))
            {
                return;
            }
            if ((this.ListChanged != null))
            {
                this.ListChanged(this, e);
            }
        }
        
        public void AddRange(System.Collections.Generic.IEnumerable<SoftFluent.SqlServerInMemory.ContactSource> collection)
        {
            CodeFluent.Runtime.Utilities.ConvertUtilities.AddRange(this, collection);
        }
        
        private void OnItemKeyChanged(object sender, CodeFluent.Runtime.Utilities.KeyChangedEventArgs<int> e)
        {
            if ((e == null))
            {
                throw new System.ArgumentNullException("e");
            }
            SoftFluent.SqlServerInMemory.ContactSource existing;
            if ((this.BaseTable.TryGetValue(e.OldKey, out existing) == false))
            {
                return;
            }
            if (((sender != null) 
                        && (typeof(CodeFluent.Runtime.Utilities.IKeyable<int>).IsAssignableFrom(sender.GetType()) == true)))
            {
                CodeFluent.Runtime.Utilities.IKeyable<int> item = ((CodeFluent.Runtime.Utilities.IKeyable<int>)(sender));
                try
                {
                    this.BaseTable.Add(item.Key, existing);
                }
                catch (System.ArgumentNullException ane)
                {
                    throw new System.ArgumentNullException(SoftFluent.SqlServerInMemory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.VoidCollectionKey, "SoftFluent.SqlServerInMemory.ContactSourceCollection", ((CodeFluent.Runtime.ICodeFluentEntity)(item)).EntityKey), ane);
                }
                catch (System.ArgumentException ae)
                {
                    throw new System.ArgumentException(SoftFluent.SqlServerInMemory.Resources.Manager.GetUserMessage(null, CodeFluent.Runtime.UserExceptionType.ItemAlreadyAdded, "SoftFluent.SqlServerInMemory.ContactSourceCollection", item.Key), ae);
                }
                this.BaseTable.Remove(e.OldKey);
            }
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Select, true)]
        public static SoftFluent.SqlServerInMemory.ContactSourceCollection PageLoadAll(int pageIndex, int pageSize)
        {
            return SoftFluent.SqlServerInMemory.ContactSourceCollection.PageLoadAll(pageIndex, pageSize, null);
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Update, true)]
        public static bool Save(SoftFluent.SqlServerInMemory.ContactSource contactSource)
        {
            if ((contactSource == null))
            {
                return false;
            }
            bool ret = contactSource.Save();
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Insert, true)]
        public static bool Insert(SoftFluent.SqlServerInMemory.ContactSource contactSource)
        {
            bool ret = SoftFluent.SqlServerInMemory.ContactSource.Save(contactSource);
            return ret;
        }
        
        [System.ComponentModel.DataObjectMethodAttribute(System.ComponentModel.DataObjectMethodType.Delete, true)]
        public static bool Delete(SoftFluent.SqlServerInMemory.ContactSource contactSource)
        {
            if ((contactSource == null))
            {
                return false;
            }
            bool ret = contactSource.Delete();
            return ret;
        }
    }
}
