//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CodeFluent.Runtime.Utilities.CodeFluentGeneratedAttribute("1.0.61214.0762", "CodeFluent Entities generated (http://www.softfluent.com). Date: Thursday, 13 Feb" +
    "ruary 2014 19:31.", CodeFluent.Runtime.Utilities.CodeFluentGeneratedAttributeOptions.CompiledWithVisualStudio, 2391010938u)]

namespace ContactManager.Proxy
{
    using CodeFluent.Runtime;
    using CodeFluent.Runtime.Utilities;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.61214.0762")]
    public sealed partial class Constants
    {
        
        public const string ContactManagerStoreName = "ContactManager";
        
        public static CodeFluent.Runtime.ServiceModel.ISafeClosable[] SafeClosables = new CodeFluent.Runtime.ServiceModel.ISafeClosable[] {
                ContactManager.Proxy.Address.WcfClient.Current,
                ContactManager.Proxy.Contact.WcfClient.Current,
                ContactManager.Proxy.ContactSource.WcfClient.Current,
                ContactManager.Proxy.User.WcfClient.Current,
                ContactManager.Proxy.User.WcfBinaryClient.Current};
        
        private Constants()
        {
        }
    }
}
