//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManager.Web
{
    using CodeFluent.Runtime;
    using CodeFluent.Runtime.Utilities;
    
    
    // CodeFluent Entities generated (http://www.softfluent.com). Date: Thursday, 13 February 2014 19:31.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.61214.0762")]
    public partial class HttpHandler : CodeFluent.Runtime.Web.UI.BinaryLargeObjectHttpHandler
    {
        
        private CodeFluent.Runtime.CodeFluentContext _context;
        
        public override CodeFluent.Runtime.CodeFluentContext CodeFluentContext
        {
            get
            {
                if ((this._context == null))
                {
                    if ((this.EntityClrFullTypeName == "ContactManager.User"))
                    {
                        this._context = CodeFluentContext.Get(ContactManager.Constants.ContactManagerStoreName);
                        return this._context;
                    }
                    this._context = CodeFluentContext.Get(ContactManager.Constants.ContactManagerStoreName);
                }
                return this._context;
            }
        }
        
        public override CodeFluent.Runtime.BinaryServices.BinaryLargeObject LoadBinaryLargeObject(System.Web.HttpContext context, string propertyName, object[] identifiersValues)
        {
            if ((this.EntityClrFullTypeName == "ContactManager.User"))
            {
                ContactManager.User User = ContactManager.User.Load(((int)(ConvertUtilities.ChangeType(identifiersValues[0], typeof(int), -1))));
                if ((User == null))
                {
                    return null;
                }
                if ((propertyName == "User_Photo"))
                {
                    return User.Photo;
                }
            }
            return null;
        }
    }
}
