//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CodeFluent.Runtime.Utilities.CodeFluentGeneratedAttribute("1.0.61214.0786", "CodeFluent Entities generated (http://www.softfluent.com). Date: Monday, 03 Novem" +
    "ber 2014 12:12.", CodeFluent.Runtime.Utilities.CodeFluentGeneratedAttributeOptions.CompiledWithVisualStudio, 863835095u)]

namespace SoftFluent.Samples.SignalR.Proxy
{
    using CodeFluent.Runtime;
    using CodeFluent.Runtime.Utilities;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CodeFluent Entities", "1.0.61214.0786")]
    public sealed partial class Constants
    {
        
        public const string SoftFluent_Samples_SignalRStoreName = "SoftFluent.Samples.SignalR";
        
        public static CodeFluent.Runtime.ServiceModel.ISafeClosable[] SafeClosables = new CodeFluent.Runtime.ServiceModel.ISafeClosable[] {
                SoftFluent.Samples.SignalR.Proxy.Customer.WcfClient.Current};
        
        private Constants()
        {
        }
    }
}
